name: Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Setup
        run: |
          sudo apt-get update && sudo apt-get install -y cmake git g++ libtbb-dev libmpfr-dev libgmp-dev libpython3-dev python3 python3-distutils
      - name: Clone
        uses: actions/checkout@v3
      - name: Compile
        run: |
          git config --global --add safe.directory /__w/vpmr/vpmr
          git submodule update --init --recursive
          sed -i 's/3.24/3.13/g' CMakeLists.txt
          mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
          make -j"$(nproc)"
          ./vpmr -h
          echo "exp(-t^2/2)" > k
          ./vpmr -nc 5 -n 20 -d 100 -q 400 -e 1e-9 -k k -w -s
          for SRC in `find . | egrep '\.o'`; do gcov -n $SRC > /dev/null; done
          python3 -c "import _pyvpmr;print(_pyvpmr.vpmr())"
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build
        run: pip install --verbose .
      - name: Test
        run: python3 test/test.py
      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          gcov: true
