name: Docker
on:
  push:
    branches: [ master ]
jobs:
  ubuntu-dev:
    if: ${{!contains(github.event.head_commit.message, '[skip]')}}
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Package
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package_name: vmpr
          untagged_only: false
          owner_type: 'user'
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./resource/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tlcfem/vpmr:latest
            ghcr.io/tlcfem/vmpr:latest
