name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  fedora:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    container: fedora:36
    steps:
      - name: Setup
        run: |
          echo "SP_TIME=daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          dnf upgrade --refresh -y
          dnf install gcc g++ gfortran cmake tbb-devel mpfr-devel gmp-devel git -y
      - name: Clone
        uses: actions/checkout@v3
      - name: Compile
        run: |
          git config --global --add safe.directory /__w/vpmr/vpmr
          git submodule update --init --recursive
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j"$(nproc)"
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vpmr
          asset_name: vpmr
          tag: latest
          prerelease: false
          overwrite: true
