jobs:
  build_sdist:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup
        run: |
          sed -i -E 's/^version = "[0-9]{6}"$/version = "'"$(date +%y%m%d)"'"/' pyproject.toml
          cd eigen && git apply ../parallelize.patch && cd ..
          pipx run build --sdist
          pipx run twine check dist/*
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: pyvpmr-sdist
          path: dist/*.tar.gz
  build_wheels:
    name: Wheels
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup
        run: |
          perl -i -pe 's/^version = "[0-9]{6}"$/version = "'$(date +%y%m%d)'"/' pyproject.toml
          cd eigen && git apply ../parallelize.patch && cd ..
      - env:
          MACOSX_DEPLOYMENT_TARGET: '15'
        if: contains(matrix.os, 'macos-15')
        name: CI Build Wheel macOS 15
        uses: pypa/cibuildwheel@v4.2
      - if: contains(matrix.os, 'ubuntu')
        name: CI Build Wheel Linux
        uses: pypa/cibuildwheel@v4.2
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: pyvpmr-${{ matrix.os }}
          path: wheelhouse/*.whl
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-15-large
          - macos-15-xlarge
  install_sdist:
    name: Install
    needs:
      - build_sdist
    runs-on: ubuntu-22.04
    steps:
      - name: Download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dist
          pattern: pyvpmr-sdist
      - name: Install
        run: |
          sudo apt-get install -y g++ libtbb-dev libmpfr-dev libgmp-dev
          pip install dist/*.tar.gz
  upload_all:
    if: contains(github.event.head_commit.message, '[publish]')
    name: Upload
    needs:
      - build_wheels
      - install_sdist
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - name: Download
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true
          path: dist
          pattern: pyvpmr*
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
name: Wheels
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
