name: Windows
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  VPMR_VERSION: ""
jobs:
  windows:
    runs-on: windows-2022
    timeout-minutes: 120
    steps:
      - name: MSYS
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git mingw-w64-x86_64-cmake mingw-w64-x86_64-tbb mingw-w64-x86_64-gcc mingw-w64-x86_64-ninja mingw-w64-x86_64-gmp mingw-w64-x86_64-mpfr mingw-w64-x86_64-7zip
      - name: Clone
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: Version
        run: |
          echo ("VPMR_VERSION="+(get-date -format "yyMMdd")) >> $env:GITHUB_ENV
      - name: Compile
        shell: msys2 {0}
        run: |
          cd eigen && git apply --ignore-space-change --ignore-whitespace ../patch_size.patch && cd ..
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_PYTHON3=OFF ..
          cmake --build .
          mkdir release
          ldd vpmr.exe
          cp vpmr.exe release
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_PYTHON3=OFF ..
          cmake --build .
          cp vpmr.exe release/vpmr-dbg.exe
          cp /mingw64/bin/libgcc_s_seh-1.dll release
          cp /mingw64/bin/libstdc++-6.dll release
          cp /mingw64/bin/libwinpthread-1.dll release
          cp /mingw64/bin/libgmp-10.dll release
          cp /mingw64/bin/libmpfr-6.dll release
          cp /mingw64/bin/libtbb12.dll release
          cd release
          7z a ../../vpmr-${{ env.VPMR_VERSION }}-win.7z *
      - name: Release
        id: release
        if: contains(github.event.head_commit.message, '[publish]')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vpmr-${{ env.VPMR_VERSION }}-win.7z
          asset_name: vpmr-${{ env.VPMR_VERSION }}-win.7z
          tag: v${{ env.VPMR_VERSION }}
          prerelease: false
          overwrite: true
      - name: VirusTotal
        if: steps.release.outputs.release_id
        uses: cssnr/virustotal-action@feature-catch-404
        with:
          vt_api_key: ${{ secrets.VIRUSTOTAL_KEY }}
          release_id: v${{ env.VPMR_VERSION }}
          release_heading: "### 🛡️ VirusTotal Results"
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: vpmr-${{ env.VPMR_VERSION }}-win.7z
          path: vpmr-${{ env.VPMR_VERSION }}-win.7z
